### PR TITLE
fix a wrong PA address width in tagcache

### PR DESCRIPTION
**Pull request by wsong83**
Currently the ci-travis failed because the dependency on sbt 0.13.8 cannot resolved. Seems the ci-travis checking has been left defunct for a long time.

### CODE REVIEW

**Comment by jrrk** [comment]
Dear Wei,
  sbt 0.13.8 is rather old. The sbt of the recently released refresh-v0.6 branch (the one with the long-awaited upgrade to Rocket compressed instructions and run/halt debug) uses sbt 1.1.1. So I suppose support for this version has been dropped upstream by somebody. For the latest release, Travis-CI is alive and well as far as I am aware. So the question is what to do to get the tag-cache version of Rocket, that you put so much effort into, to get it working again. If you have a suggested patch I am happy to merge it with the master branch which I think we decided to leave alone since it is so radically different in directory structure to what we are doing now. Nobody else understands Travis-CI like you do I suspect.

**Comment by asb** [comment]
We should sync master to the refresh-0.6 branch, and leave previous releases in separate branches.

**Comment by wsong83** [comment]
My mistake. I was meant to merge bugfix into the minion-v0.4.
Will try to fix the ci-travis later when time is available.

**Comment by wsong83** [comment]
ci-travis fixed.

**Pull request merged**
