### PR TITLE
Bugfix for the tag cache concurrency issue

### PR DESCRIPTION
**Pull request by wsong83**
To handle the concurrency issue in tag cache

- redesign the control logic
- constrain concurrency by locking the top level line
- avoid using queues to allow parallel transactions in waiting
- always lock before write

### CODE REVIEW

**Comment by wsong83** [comment]
@jrrk 

There are some problems with the minion-soc.
Right now, I can boot Linux on FPGA using a a bitstream from Flash and boot.bin from SD.
However, I fail to mount the SD to Linux.
Also if a run 'h' command in selftest, it reports sd timeout multiple times and then freeze (in hardware sense as I cannot reset using trace debugger either)!

Would you please have a look and try to fix it? Then I can have this merged to release as soon as possible.

WTB, there is no straight-forward way to run a FPGA simulation. Even I say disable the minion-sd, printf functions still go into the minion programs in the bare-metal/driver directories.

**Comment by wsong83** [comment]
@jrrk Would you please have a look and verify that this PR would not affect the minion side, a.k.a. it still allows Linux to be correctly booted and SD correctly mounted. Then I think it is time to have it merged.

**Comment by jrrk** [comment]
I have built and installed the update branch, and there were no problems that I could see. However the Linux patches seem not to be up-to-date (there is no scrolling in the VGA terminal window). This needs investigating before the merge is finalised.

**Comment by wsong83** [comment]
@jrrk Since the linux patch is now merged to minion-v0.4 in riscv-linux, I think this PR is ready to go after revert your last commit?

**Comment by jrrk** [comment]
It should be ready to go after one last run through Travis

**Comment by wsong83** [comment]
Thanks!

**Pull request merged**
