### PR TITLE
TagCache support re-added

### PR DESCRIPTION
**Pull request by zzyppo**

### CODE REVIEW

**Comment by wsong83** [comment]
This check will fail as submodule is not committed yet.

**Comment by zzyppo** [comment]
Hmm . Well I have not initialized them. I only made a checkout on the main repo for this merge. What exactly do I have to do?

**Comment by zzyppo** [comment]
Oh it worked as I see. Nice

**Comment by wsong83** [comment]
Nothing, I will update submodules later. Thanks.

**Comment by zzyppo** [comment]
Thank you

**Pull request merged**
